### PR TITLE
Upgrading OneNote library to .NET Standard

### LINKED ISSUE #7: Projects should target .NET Standard for better availability
Currently the projects target .NET Framework, which limits their availability to just other .NET Framework projects. If instead they target .NET Standard 2.0, they could be consumed by both .NET Framework **and** .NET Core projects. I checked the OneNote project and there's nothing preventing it from being switched over, not sure about the others. The could be done piecemeal as well.

### PR DESCRIPTION
**Pull request by palenshus**
Fixes #7

* Converting Common, OneNote, Excel, and Outlook projects to .NET Standard 2.0. This will allow them to be consumed by both .NET Framework and .NET (Core) projects
* Fixing Excel tests to be runnable in US region (MM-DD-YYYY)
* Speeding up Outlook tests by using .Any() instead of .Count(). Any() doesn't require traversing the whole enumeration
* Cleaning up a few IDE code suggestions

### CODE REVIEW

**Comment by palenshus** [comment]
Thanks for the quick turnaround! Now we just need to get the nuget updated. I can help with that if you'd like!

**Comment by scipbe** [comment]
Any help is appreciated because my freetime is very limited

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Union Palenshus ***@***.***>
Verzonden: Monday, May 23, 2022 7:33:05 PM
Aan: scipbe/ScipBe-Common-Office ***@***.***>
CC: Stefan Cruysberghs ***@***.***>; State change ***@***.***>
Onderwerp: Re: [scipbe/ScipBe-Common-Office] Upgrading OneNote library to .NET Standard (PR #8)


Thanks for the quick turnaround! Now we just need to get the nuget updated. I can help with that if you'd like!

**Comment by palenshus** [comment]
If you'd like to add me as an owner to the nuget packages, I can take care of the rest, my nuget ID is "unionp". If you'd prefer not to do that, no problem, just let me know how I can help

**Comment by palenshus** [comment]
Nice, thanks! Got a new PR for updating the nuget and such: https://github.com/scipbe/ScipBe-Common-Office/pull/9

**Pull request merged**
